name: calm_space
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/photos/calm.png
    - assets/photos/journaling.png
    - assets/photos/mood_tracking.png
    - assets/photos/coping_tips.png

  fonts:
    - family: Cursive
      fonts:
        - asset: assets/fonts/Cursive.ttf
    - family: AppleGaramond
      fonts:
        - asset: assets/fonts/AppleGaramond.ttf
