name: calm_space
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  table_calendar: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/photos/calm.png
    - assets/photos/journaling.png
    - assets/photos/mood_tracking.png
    - assets/photos/coping_tips.png
    - assets/photos/happy.png
    - assets/photos/angry.png
    - assets/photos/calm_.png
    - assets/photos/sad.png
    - assets/photos/disappointed.png
    - assets/photos/scared.png
    - assets/photos/worried.png
    - assets/photos/frustrated.png
    - assets/photos/unknown.png

  fonts:
    - family: Cursive
      fonts:
        - asset: assets/fonts/Cursive.ttf
    - family: AppleGaramond
      fonts:
        - asset: assets/fonts/AppleGaramond.ttf
    - family: Sans
      fonts:
        - asset: assets/fonts/Sans.ttf
